/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai.index'
import { Route as ApiChatConversationIdRouteImport } from './routes/api/chat.$conversationId'
import { Route as AuthenticatedToolsMemoRouteImport } from './routes/_authenticated/tools.memo'
import { Route as AuthenticatedToolsHomeworkRouteImport } from './routes/_authenticated/tools.homework'
import { Route as AuthenticatedToolsExercisesRouteImport } from './routes/_authenticated/tools.exercises'
import { Route as AuthenticatedToolsCountdownRouteImport } from './routes/_authenticated/tools.countdown'
import { Route as AuthenticatedToolsCalculatorRouteImport } from './routes/_authenticated/tools.calculator'
import { Route as AuthenticatedTeacherAvailabilityRouteImport } from './routes/_authenticated/teacher.availability'
import { Route as AuthenticatedLiveSessionIdRouteImport } from './routes/_authenticated/live.$sessionId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedCommunityThreadIdRouteImport } from './routes/_authenticated/community.$threadId'
import { Route as AuthenticatedAiSheetsRouteImport } from './routes/_authenticated/ai.sheets'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin_.moderation'
import { Route as AuthenticatedAdminArchiveRouteImport } from './routes/_authenticated/admin_.archive'
import { Route as ApiPublicHooksTaskRemindersRouteImport } from './routes/api/public/hooks/task-reminders'
import { Route as AuthenticatedToolsMemoSheetIdRouteImport } from './routes/_authenticated/tools.memo.$sheetId'
import { Route as AuthenticatedTeacherCoursesNewRouteImport } from './routes/_authenticated/teacher.courses.new'
import { Route as AuthenticatedSessionsBookTeacherIdRouteImport } from './routes/_authenticated/sessions.book.$teacherId'
import { Route as AuthenticatedAiSheetsSheetIdRouteImport } from './routes/_authenticated/ai.sheets.$sheetId'
import { Route as AuthenticatedAiExamNewRouteImport } from './routes/_authenticated/ai.exam.new'
import { Route as AuthenticatedAiExamExamIdRouteImport } from './routes/_authenticated/ai.exam.$examId'
import { Route as AuthenticatedAiCConversationIdRouteImport } from './routes/_authenticated/ai.c.$conversationId'
import { Route as AuthenticatedTeacherCoursesCourseIdChaptersRouteImport } from './routes/_authenticated/teacher.courses.$courseId.chapters'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const ApiChatConversationIdRoute = ApiChatConversationIdRouteImport.update({
  id: '/api/chat/$conversationId',
  path: '/api/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsMemoRoute = AuthenticatedToolsMemoRouteImport.update({
  id: '/tools/memo',
  path: '/tools/memo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsHomeworkRoute =
  AuthenticatedToolsHomeworkRouteImport.update({
    id: '/tools/homework',
    path: '/tools/homework',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsExercisesRoute =
  AuthenticatedToolsExercisesRouteImport.update({
    id: '/tools/exercises',
    path: '/tools/exercises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsCountdownRoute =
  AuthenticatedToolsCountdownRouteImport.update({
    id: '/tools/countdown',
    path: '/tools/countdown',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsCalculatorRoute =
  AuthenticatedToolsCalculatorRouteImport.update({
    id: '/tools/calculator',
    path: '/tools/calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAvailabilityRoute =
  AuthenticatedTeacherAvailabilityRouteImport.update({
    id: '/teacher/availability',
    path: '/teacher/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionIdRoute =
  AuthenticatedLiveSessionIdRouteImport.update({
    id: '/live/$sessionId',
    path: '/live/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityThreadIdRoute =
  AuthenticatedCommunityThreadIdRouteImport.update({
    id: '/community/$threadId',
    path: '/community/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSheetsRoute = AuthenticatedAiSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin_/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminArchiveRoute =
  AuthenticatedAdminArchiveRouteImport.update({
    id: '/admin_/archive',
    path: '/admin/archive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksTaskRemindersRoute =
  ApiPublicHooksTaskRemindersRouteImport.update({
    id: '/api/public/hooks/task-reminders',
    path: '/api/public/hooks/task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedToolsMemoSheetIdRoute =
  AuthenticatedToolsMemoSheetIdRouteImport.update({
    id: '/$sheetId',
    path: '/$sheetId',
    getParentRoute: () => AuthenticatedToolsMemoRoute,
  } as any)
const AuthenticatedTeacherCoursesNewRoute =
  AuthenticatedTeacherCoursesNewRouteImport.update({
    id: '/teacher/courses/new',
    path: '/teacher/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsBookTeacherIdRoute =
  AuthenticatedSessionsBookTeacherIdRouteImport.update({
    id: '/sessions/book/$teacherId',
    path: '/sessions/book/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSheetsSheetIdRoute =
  AuthenticatedAiSheetsSheetIdRouteImport.update({
    id: '/$sheetId',
    path: '/$sheetId',
    getParentRoute: () => AuthenticatedAiSheetsRoute,
  } as any)
const AuthenticatedAiExamNewRoute = AuthenticatedAiExamNewRouteImport.update({
  id: '/exam/new',
  path: '/exam/new',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiExamExamIdRoute =
  AuthenticatedAiExamExamIdRouteImport.update({
    id: '/exam/$examId',
    path: '/exam/$examId',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiCConversationIdRoute =
  AuthenticatedAiCConversationIdRouteImport.update({
    id: '/c/$conversationId',
    path: '/c/$conversationId',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdChaptersRoute =
  AuthenticatedTeacherCoursesCourseIdChaptersRouteImport.update({
    id: '/teacher/courses/$courseId/chapters',
    path: '/teacher/courses/$courseId/chapters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRouteWithChildren
  '/archive': typeof AuthenticatedArchiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library/': typeof LibraryIndexRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/tools/exercises': typeof AuthenticatedToolsExercisesRoute
  '/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/tools/memo': typeof AuthenticatedToolsMemoRouteWithChildren
  '/api/chat/$conversationId': typeof ApiChatConversationIdRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/ai/c/$conversationId': typeof AuthenticatedAiCConversationIdRoute
  '/ai/exam/$examId': typeof AuthenticatedAiExamExamIdRoute
  '/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
  '/teacher/courses/$courseId/chapters': typeof AuthenticatedTeacherCoursesCourseIdChaptersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library': typeof LibraryIndexRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/tools/exercises': typeof AuthenticatedToolsExercisesRoute
  '/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/tools/memo': typeof AuthenticatedToolsMemoRouteWithChildren
  '/api/chat/$conversationId': typeof ApiChatConversationIdRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/ai/c/$conversationId': typeof AuthenticatedAiCConversationIdRoute
  '/ai/exam/$examId': typeof AuthenticatedAiExamExamIdRoute
  '/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
  '/teacher/courses/$courseId/chapters': typeof AuthenticatedTeacherCoursesCourseIdChaptersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRouteWithChildren
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library/': typeof LibraryIndexRoute
  '/_authenticated/admin_/archive': typeof AuthenticatedAdminArchiveRoute
  '/_authenticated/admin_/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/_authenticated/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/_authenticated/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/_authenticated/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/_authenticated/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/_authenticated/tools/exercises': typeof AuthenticatedToolsExercisesRoute
  '/_authenticated/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/_authenticated/tools/memo': typeof AuthenticatedToolsMemoRouteWithChildren
  '/api/chat/$conversationId': typeof ApiChatConversationIdRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/ai/c/$conversationId': typeof AuthenticatedAiCConversationIdRoute
  '/_authenticated/ai/exam/$examId': typeof AuthenticatedAiExamExamIdRoute
  '/_authenticated/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/_authenticated/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/_authenticated/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/_authenticated/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/_authenticated/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
  '/_authenticated/teacher/courses/$courseId/chapters': typeof AuthenticatedTeacherCoursesCourseIdChaptersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/admin'
    | '/ai'
    | '/archive'
    | '/dashboard'
    | '/invite'
    | '/onboarding'
    | '/courses/$courseId'
    | '/sessions/$sessionId'
    | '/library/'
    | '/admin/archive'
    | '/admin/moderation'
    | '/ai/sheets'
    | '/community/$threadId'
    | '/groups/$groupId'
    | '/live/$sessionId'
    | '/teacher/availability'
    | '/tools/calculator'
    | '/tools/countdown'
    | '/tools/exercises'
    | '/tools/homework'
    | '/tools/memo'
    | '/api/chat/$conversationId'
    | '/ai/'
    | '/community/'
    | '/groups/'
    | '/teacher/'
    | '/tools/'
    | '/ai/c/$conversationId'
    | '/ai/exam/$examId'
    | '/ai/exam/new'
    | '/ai/sheets/$sheetId'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/new'
    | '/tools/memo/$sheetId'
    | '/api/public/hooks/task-reminders'
    | '/teacher/courses/$courseId/chapters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/admin'
    | '/archive'
    | '/dashboard'
    | '/invite'
    | '/onboarding'
    | '/courses/$courseId'
    | '/sessions/$sessionId'
    | '/library'
    | '/admin/archive'
    | '/admin/moderation'
    | '/ai/sheets'
    | '/community/$threadId'
    | '/groups/$groupId'
    | '/live/$sessionId'
    | '/teacher/availability'
    | '/tools/calculator'
    | '/tools/countdown'
    | '/tools/exercises'
    | '/tools/homework'
    | '/tools/memo'
    | '/api/chat/$conversationId'
    | '/ai'
    | '/community'
    | '/groups'
    | '/teacher'
    | '/tools'
    | '/ai/c/$conversationId'
    | '/ai/exam/$examId'
    | '/ai/exam/new'
    | '/ai/sheets/$sheetId'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/new'
    | '/tools/memo/$sheetId'
    | '/api/public/hooks/task-reminders'
    | '/teacher/courses/$courseId/chapters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/archive'
    | '/_authenticated/dashboard'
    | '/_authenticated/invite'
    | '/_authenticated/onboarding'
    | '/courses/$courseId'
    | '/sessions/$sessionId'
    | '/library/'
    | '/_authenticated/admin_/archive'
    | '/_authenticated/admin_/moderation'
    | '/_authenticated/ai/sheets'
    | '/_authenticated/community/$threadId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/live/$sessionId'
    | '/_authenticated/teacher/availability'
    | '/_authenticated/tools/calculator'
    | '/_authenticated/tools/countdown'
    | '/_authenticated/tools/exercises'
    | '/_authenticated/tools/homework'
    | '/_authenticated/tools/memo'
    | '/api/chat/$conversationId'
    | '/_authenticated/ai/'
    | '/_authenticated/community/'
    | '/_authenticated/groups/'
    | '/_authenticated/teacher/'
    | '/_authenticated/tools/'
    | '/_authenticated/ai/c/$conversationId'
    | '/_authenticated/ai/exam/$examId'
    | '/_authenticated/ai/exam/new'
    | '/_authenticated/ai/sheets/$sheetId'
    | '/_authenticated/sessions/book/$teacherId'
    | '/_authenticated/teacher/courses/new'
    | '/_authenticated/tools/memo/$sheetId'
    | '/api/public/hooks/task-reminders'
    | '/_authenticated/teacher/courses/$courseId/chapters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachersRoute: typeof TeachersRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ApiChatConversationIdRoute: typeof ApiChatConversationIdRoute
  ApiPublicHooksTaskRemindersRoute: typeof ApiPublicHooksTaskRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/api/chat/$conversationId': {
      id: '/api/chat/$conversationId'
      path: '/api/chat/$conversationId'
      fullPath: '/api/chat/$conversationId'
      preLoaderRoute: typeof ApiChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/memo': {
      id: '/_authenticated/tools/memo'
      path: '/tools/memo'
      fullPath: '/tools/memo'
      preLoaderRoute: typeof AuthenticatedToolsMemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/homework': {
      id: '/_authenticated/tools/homework'
      path: '/tools/homework'
      fullPath: '/tools/homework'
      preLoaderRoute: typeof AuthenticatedToolsHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/exercises': {
      id: '/_authenticated/tools/exercises'
      path: '/tools/exercises'
      fullPath: '/tools/exercises'
      preLoaderRoute: typeof AuthenticatedToolsExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/countdown': {
      id: '/_authenticated/tools/countdown'
      path: '/tools/countdown'
      fullPath: '/tools/countdown'
      preLoaderRoute: typeof AuthenticatedToolsCountdownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/calculator': {
      id: '/_authenticated/tools/calculator'
      path: '/tools/calculator'
      fullPath: '/tools/calculator'
      preLoaderRoute: typeof AuthenticatedToolsCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/availability': {
      id: '/_authenticated/teacher/availability'
      path: '/teacher/availability'
      fullPath: '/teacher/availability'
      preLoaderRoute: typeof AuthenticatedTeacherAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/$sessionId': {
      id: '/_authenticated/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof AuthenticatedLiveSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/$threadId': {
      id: '/_authenticated/community/$threadId'
      path: '/community/$threadId'
      fullPath: '/community/$threadId'
      preLoaderRoute: typeof AuthenticatedCommunityThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/sheets': {
      id: '/_authenticated/ai/sheets'
      path: '/sheets'
      fullPath: '/ai/sheets'
      preLoaderRoute: typeof AuthenticatedAiSheetsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/admin_/moderation': {
      id: '/_authenticated/admin_/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/archive': {
      id: '/_authenticated/admin_/archive'
      path: '/admin/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AuthenticatedAdminArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/task-reminders': {
      id: '/api/public/hooks/task-reminders'
      path: '/api/public/hooks/task-reminders'
      fullPath: '/api/public/hooks/task-reminders'
      preLoaderRoute: typeof ApiPublicHooksTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/memo/$sheetId': {
      id: '/_authenticated/tools/memo/$sheetId'
      path: '/$sheetId'
      fullPath: '/tools/memo/$sheetId'
      preLoaderRoute: typeof AuthenticatedToolsMemoSheetIdRouteImport
      parentRoute: typeof AuthenticatedToolsMemoRoute
    }
    '/_authenticated/teacher/courses/new': {
      id: '/_authenticated/teacher/courses/new'
      path: '/teacher/courses/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/book/$teacherId': {
      id: '/_authenticated/sessions/book/$teacherId'
      path: '/sessions/book/$teacherId'
      fullPath: '/sessions/book/$teacherId'
      preLoaderRoute: typeof AuthenticatedSessionsBookTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/sheets/$sheetId': {
      id: '/_authenticated/ai/sheets/$sheetId'
      path: '/$sheetId'
      fullPath: '/ai/sheets/$sheetId'
      preLoaderRoute: typeof AuthenticatedAiSheetsSheetIdRouteImport
      parentRoute: typeof AuthenticatedAiSheetsRoute
    }
    '/_authenticated/ai/exam/new': {
      id: '/_authenticated/ai/exam/new'
      path: '/exam/new'
      fullPath: '/ai/exam/new'
      preLoaderRoute: typeof AuthenticatedAiExamNewRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/exam/$examId': {
      id: '/_authenticated/ai/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/ai/exam/$examId'
      preLoaderRoute: typeof AuthenticatedAiExamExamIdRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/c/$conversationId': {
      id: '/_authenticated/ai/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/ai/c/$conversationId'
      preLoaderRoute: typeof AuthenticatedAiCConversationIdRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/teacher/courses/$courseId/chapters': {
      id: '/_authenticated/teacher/courses/$courseId/chapters'
      path: '/teacher/courses/$courseId/chapters'
      fullPath: '/teacher/courses/$courseId/chapters'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdChaptersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAiSheetsRouteChildren {
  AuthenticatedAiSheetsSheetIdRoute: typeof AuthenticatedAiSheetsSheetIdRoute
}

const AuthenticatedAiSheetsRouteChildren: AuthenticatedAiSheetsRouteChildren = {
  AuthenticatedAiSheetsSheetIdRoute: AuthenticatedAiSheetsSheetIdRoute,
}

const AuthenticatedAiSheetsRouteWithChildren =
  AuthenticatedAiSheetsRoute._addFileChildren(
    AuthenticatedAiSheetsRouteChildren,
  )

interface AuthenticatedAiRouteChildren {
  AuthenticatedAiSheetsRoute: typeof AuthenticatedAiSheetsRouteWithChildren
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedAiCConversationIdRoute: typeof AuthenticatedAiCConversationIdRoute
  AuthenticatedAiExamExamIdRoute: typeof AuthenticatedAiExamExamIdRoute
  AuthenticatedAiExamNewRoute: typeof AuthenticatedAiExamNewRoute
}

const AuthenticatedAiRouteChildren: AuthenticatedAiRouteChildren = {
  AuthenticatedAiSheetsRoute: AuthenticatedAiSheetsRouteWithChildren,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedAiCConversationIdRoute: AuthenticatedAiCConversationIdRoute,
  AuthenticatedAiExamExamIdRoute: AuthenticatedAiExamExamIdRoute,
  AuthenticatedAiExamNewRoute: AuthenticatedAiExamNewRoute,
}

const AuthenticatedAiRouteWithChildren = AuthenticatedAiRoute._addFileChildren(
  AuthenticatedAiRouteChildren,
)

interface AuthenticatedToolsMemoRouteChildren {
  AuthenticatedToolsMemoSheetIdRoute: typeof AuthenticatedToolsMemoSheetIdRoute
}

const AuthenticatedToolsMemoRouteChildren: AuthenticatedToolsMemoRouteChildren =
  {
    AuthenticatedToolsMemoSheetIdRoute: AuthenticatedToolsMemoSheetIdRoute,
  }

const AuthenticatedToolsMemoRouteWithChildren =
  AuthenticatedToolsMemoRoute._addFileChildren(
    AuthenticatedToolsMemoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRouteWithChildren
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminArchiveRoute: typeof AuthenticatedAdminArchiveRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedCommunityThreadIdRoute: typeof AuthenticatedCommunityThreadIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedLiveSessionIdRoute: typeof AuthenticatedLiveSessionIdRoute
  AuthenticatedTeacherAvailabilityRoute: typeof AuthenticatedTeacherAvailabilityRoute
  AuthenticatedToolsCalculatorRoute: typeof AuthenticatedToolsCalculatorRoute
  AuthenticatedToolsCountdownRoute: typeof AuthenticatedToolsCountdownRoute
  AuthenticatedToolsExercisesRoute: typeof AuthenticatedToolsExercisesRoute
  AuthenticatedToolsHomeworkRoute: typeof AuthenticatedToolsHomeworkRoute
  AuthenticatedToolsMemoRoute: typeof AuthenticatedToolsMemoRouteWithChildren
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedSessionsBookTeacherIdRoute: typeof AuthenticatedSessionsBookTeacherIdRoute
  AuthenticatedTeacherCoursesNewRoute: typeof AuthenticatedTeacherCoursesNewRoute
  AuthenticatedTeacherCoursesCourseIdChaptersRoute: typeof AuthenticatedTeacherCoursesCourseIdChaptersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRouteWithChildren,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminArchiveRoute: AuthenticatedAdminArchiveRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedCommunityThreadIdRoute: AuthenticatedCommunityThreadIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedLiveSessionIdRoute: AuthenticatedLiveSessionIdRoute,
  AuthenticatedTeacherAvailabilityRoute: AuthenticatedTeacherAvailabilityRoute,
  AuthenticatedToolsCalculatorRoute: AuthenticatedToolsCalculatorRoute,
  AuthenticatedToolsCountdownRoute: AuthenticatedToolsCountdownRoute,
  AuthenticatedToolsExercisesRoute: AuthenticatedToolsExercisesRoute,
  AuthenticatedToolsHomeworkRoute: AuthenticatedToolsHomeworkRoute,
  AuthenticatedToolsMemoRoute: AuthenticatedToolsMemoRouteWithChildren,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedSessionsBookTeacherIdRoute:
    AuthenticatedSessionsBookTeacherIdRoute,
  AuthenticatedTeacherCoursesNewRoute: AuthenticatedTeacherCoursesNewRoute,
  AuthenticatedTeacherCoursesCourseIdChaptersRoute:
    AuthenticatedTeacherCoursesCourseIdChaptersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachersRoute: TeachersRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ApiChatConversationIdRoute: ApiChatConversationIdRoute,
  ApiPublicHooksTaskRemindersRoute: ApiPublicHooksTaskRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
