/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai.index'
import { Route as AuthenticatedTeacherAvailabilityRouteImport } from './routes/_authenticated/teacher.availability'
import { Route as AuthenticatedAiSheetsRouteImport } from './routes/_authenticated/ai.sheets'
import { Route as AuthenticatedTeacherCoursesNewRouteImport } from './routes/_authenticated/teacher.courses.new'
import { Route as AuthenticatedAiSheetsSheetIdRouteImport } from './routes/_authenticated/ai.sheets.$sheetId'
import { Route as AuthenticatedAiExamNewRouteImport } from './routes/_authenticated/ai.exam.new'
import { Route as AuthenticatedAiExamRouteImport } from './routes/_authenticated/ai.exam.'
import { Route as AuthenticatedAiCRouteImport } from './routes/_authenticated/ai.c.'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedTeacherAvailabilityRoute =
  AuthenticatedTeacherAvailabilityRouteImport.update({
    id: '/teacher/availability',
    path: '/teacher/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSheetsRoute = AuthenticatedAiSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedTeacherCoursesNewRoute =
  AuthenticatedTeacherCoursesNewRouteImport.update({
    id: '/teacher/courses/new',
    path: '/teacher/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSheetsSheetIdRoute =
  AuthenticatedAiSheetsSheetIdRouteImport.update({
    id: '/$sheetId',
    path: '/$sheetId',
    getParentRoute: () => AuthenticatedAiSheetsRoute,
  } as any)
const AuthenticatedAiExamNewRoute = AuthenticatedAiExamNewRouteImport.update({
  id: '/exam/new',
  path: '/exam/new',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiExamRoute = AuthenticatedAiExamRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiCRoute = AuthenticatedAiCRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/ai': typeof AuthenticatedAiRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/ai/c/': typeof AuthenticatedAiCRoute
  '/ai/exam/': typeof AuthenticatedAiExamRoute
  '/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/ai/c': typeof AuthenticatedAiCRoute
  '/ai/exam': typeof AuthenticatedAiExamRoute
  '/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
  '/_authenticated/ai': typeof AuthenticatedAiRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/_authenticated/ai/sheets': typeof AuthenticatedAiSheetsRouteWithChildren
  '/_authenticated/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/ai/c/': typeof AuthenticatedAiCRoute
  '/_authenticated/ai/exam/': typeof AuthenticatedAiExamRoute
  '/_authenticated/ai/exam/new': typeof AuthenticatedAiExamNewRoute
  '/_authenticated/ai/sheets/$sheetId': typeof AuthenticatedAiSheetsSheetIdRoute
  '/_authenticated/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/ai'
    | '/dashboard'
    | '/onboarding'
    | '/courses/$courseId'
    | '/ai/sheets'
    | '/teacher/availability'
    | '/ai/'
    | '/teacher/'
    | '/ai/c/'
    | '/ai/exam/'
    | '/ai/exam/new'
    | '/ai/sheets/$sheetId'
    | '/teacher/courses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/dashboard'
    | '/onboarding'
    | '/courses/$courseId'
    | '/ai/sheets'
    | '/teacher/availability'
    | '/ai'
    | '/teacher'
    | '/ai/c'
    | '/ai/exam'
    | '/ai/exam/new'
    | '/ai/sheets/$sheetId'
    | '/teacher/courses/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/courses'
    | '/sitemap.xml'
    | '/teachers'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/courses/$courseId'
    | '/_authenticated/ai/sheets'
    | '/_authenticated/teacher/availability'
    | '/_authenticated/ai/'
    | '/_authenticated/teacher/'
    | '/_authenticated/ai/c/'
    | '/_authenticated/ai/exam/'
    | '/_authenticated/ai/exam/new'
    | '/_authenticated/ai/sheets/$sheetId'
    | '/_authenticated/teacher/courses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/teacher/availability': {
      id: '/_authenticated/teacher/availability'
      path: '/teacher/availability'
      fullPath: '/teacher/availability'
      preLoaderRoute: typeof AuthenticatedTeacherAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/sheets': {
      id: '/_authenticated/ai/sheets'
      path: '/sheets'
      fullPath: '/ai/sheets'
      preLoaderRoute: typeof AuthenticatedAiSheetsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/teacher/courses/new': {
      id: '/_authenticated/teacher/courses/new'
      path: '/teacher/courses/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/sheets/$sheetId': {
      id: '/_authenticated/ai/sheets/$sheetId'
      path: '/$sheetId'
      fullPath: '/ai/sheets/$sheetId'
      preLoaderRoute: typeof AuthenticatedAiSheetsSheetIdRouteImport
      parentRoute: typeof AuthenticatedAiSheetsRoute
    }
    '/_authenticated/ai/exam/new': {
      id: '/_authenticated/ai/exam/new'
      path: '/exam/new'
      fullPath: '/ai/exam/new'
      preLoaderRoute: typeof AuthenticatedAiExamNewRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/exam/': {
      id: '/_authenticated/ai/exam/'
      path: '/exam'
      fullPath: '/ai/exam/'
      preLoaderRoute: typeof AuthenticatedAiExamRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/c/': {
      id: '/_authenticated/ai/c/'
      path: '/c'
      fullPath: '/ai/c/'
      preLoaderRoute: typeof AuthenticatedAiCRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
  }
}

interface AuthenticatedAiSheetsRouteChildren {
  AuthenticatedAiSheetsSheetIdRoute: typeof AuthenticatedAiSheetsSheetIdRoute
}

const AuthenticatedAiSheetsRouteChildren: AuthenticatedAiSheetsRouteChildren = {
  AuthenticatedAiSheetsSheetIdRoute: AuthenticatedAiSheetsSheetIdRoute,
}

const AuthenticatedAiSheetsRouteWithChildren =
  AuthenticatedAiSheetsRoute._addFileChildren(
    AuthenticatedAiSheetsRouteChildren,
  )

interface AuthenticatedAiRouteChildren {
  AuthenticatedAiSheetsRoute: typeof AuthenticatedAiSheetsRouteWithChildren
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedAiCRoute: typeof AuthenticatedAiCRoute
  AuthenticatedAiExamRoute: typeof AuthenticatedAiExamRoute
  AuthenticatedAiExamNewRoute: typeof AuthenticatedAiExamNewRoute
}

const AuthenticatedAiRouteChildren: AuthenticatedAiRouteChildren = {
  AuthenticatedAiSheetsRoute: AuthenticatedAiSheetsRouteWithChildren,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedAiCRoute: AuthenticatedAiCRoute,
  AuthenticatedAiExamRoute: AuthenticatedAiExamRoute,
  AuthenticatedAiExamNewRoute: AuthenticatedAiExamNewRoute,
}

const AuthenticatedAiRouteWithChildren = AuthenticatedAiRoute._addFileChildren(
  AuthenticatedAiRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTeacherAvailabilityRoute: typeof AuthenticatedTeacherAvailabilityRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherCoursesNewRoute: typeof AuthenticatedTeacherCoursesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTeacherAvailabilityRoute: AuthenticatedTeacherAvailabilityRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeacherCoursesNewRoute: AuthenticatedTeacherCoursesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
